program ::= stmt*

stmt ::= let_stmt `;` | mult_expr `;`

let_stmt ::= `:` id `=` mult_expr

mult_expr ::= add_expr ((`*`|`/`) mult_expr)+

add_expr ::= power_expr ((`+`|`-`) mult_expr)+

power_expr = unary_expr (`^` mult_expr)+

unary_expr ::= (`+`|`-`)? atom |

atom ::= number | id | `(` mult_expr `)` | id `(` mult_expr `)`
